#!/usr/bin/env bash
#
# mayhem/build.sh — build the XXL interpreter fuzz target + reproducer + upstream test suite.
#
# XXL is a small tree-walking interpreter. The fuzz surface is the reader+evaluator driven over
# a FILE argument: `xxl <file>` -> main() -> args() -> evalfile() -> parsestr()/evalin(), then
# exits (stdout is not a tty under Mayhem) — so the same binary is both the fuzz target and its
# own run-once reproducer. It is built SINGLE-THREADED (no -DTHREAD, and no STDLIBMBOX, whose
# mailboxes require threads): the interpreter core doesn't need threads to parse+evaluate input,
# and single-threaded sanitized CLI binaries are the fleet-proven fuzzable shape for interpreters.
#
# Bounding (SS6b): XXL's own `exhaust`/`recurse` verbs self-limit to an internal ~2048-step stack
# check, but an ordinary self-recursive lambda does NOT — `0 {self as 'f; x f}` spins forever
# (verified via gdb: looping in applyexpr()/xln()/xalloc(), unbounded allocation, never blocks).
# Since this is a raw process-per-input target (no libfuzzer:), a hang would stall the whole
# Mayhem campaign on one input. So the fuzz binary's `main` is renamed to `xxl_upstream_main`
# via -Dmain (fuzz build ONLY — never the test build below) and wrapped by
# mayhem/watchdog_main.c, which arms a hard ~1.5s alarm()/SIGALRM watchdog that _exit()s the
# process before any XXL code runs, regardless of what the interpreter itself does.
#
# The upstream test suite is xxl's built-in selftest (test_basics/nest/ctx/eval/logic/semantics,
# run when built -DDEBUG and invoked with no args) and keeps upstream's full -DTHREAD
# configuration and REAL (unrenamed) main() — it must stay an honest, unwatchdogged oracle.
set -euo pipefail

[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${COVERAGE_FLAGS=}"
export SANITIZER_FLAGS DEBUG_FLAGS CC MAYHEM_JOBS COVERAGE_FLAGS

cd "$SRC"

SRCS="xxl.c repl.c net.c stdlib.c verbs.c"
# Enabled stdlib modules (mirror the upstream ./c build script's default LIBRARIES set).
LIBDEFS="-DOCTA -DSTDLIBFILE -DSTDLIBGLOB -DSTDLIBMBOX -DSTDLIBNET -DSTDLIBSHAREDLIB -DSTDLIBSHELL -DSTDLIBXD"
# Fuzz-binary module set: everything except STDLIBMBOX (mailboxes hard-require -DTHREAD).
FUZZ_LIBDEFS="-DOCTA -DSTDLIBFILE -DSTDLIBGLOB -DSTDLIBNET -DSTDLIBSHAREDLIB -DSTDLIBSHELL -DSTDLIBXD"
# Upstream is pre-C99 GNU C (uses `auto`/implicit-int, implicit function decls). clang-19 defaults to
# C23 where those are hard errors, so pin the GNU C17 dialect (matches the upstream ./c gcc build) and
# silence the remaining benign warnings so -w keeps the log readable; not correctness-affecting.
STD="-std=gnu17"
# clang-19 promotes these pre-C99 constructs from warnings to hard errors; upstream relies on them
# (gcc accepts them). Explicitly demote to non-errors (-w alone can't disable default-error diags).
COMPAT="-Wno-implicit-int -Wno-implicit-function-declaration -Wno-int-conversion -Wno-error=implicit-int -Wno-error=implicit-function-declaration"
WARN="-w $COMPAT"
LINK="-pthread -ldl -lm"

# compile.h is generated by upstream's ./c script; it records the build's own compile commands.
# Regenerate it here (idempotent) so xxl.c #include "compile.h" resolves without invoking node.
gen_compile_h() {
  cat > compile.h <<EOF

#define XXL_SRC "$SRC/"
#define XXL_COMPILEOBJ "$CC -c "
#define XXL_COMPILESHARED "$CC -fPIC -shared "
#define XXL_BUILDOBJ "$CC -o "
#define XXL_BUILDSHARED "$CC -fPIC -shared "
EOF
}
gen_compile_h

# 1) Fuzz target == run-once reproducer: the real interpreter, instrumented (ASan+UBSan) and carrying
#    DWARF<4, PLUS the hard watchdog (see header comment). Built WITHOUT -DDEBUG so `xxl <file>` takes
#    the evalfile path (no selftest) and exits. -fsanitize=fuzzer-no-link is added unconditionally
#    (including when $SANITIZER_FLAGS is empty) so the interpreter itself carries SanCov coverage —
#    $SANITIZER_FLAGS alone gives no coverage instrumentation, only the sanitizer runtime.
#    Two-step compile (object files, not one multi-source invocation) so `-Dmain=xxl_upstream_main`
#    applies ONLY to upstream's sources, never to mayhem/watchdog_main.c's own real main().
rm -f ./*.o
$CC $STD $SANITIZER_FLAGS -fsanitize=fuzzer-no-link $DEBUG_FLAGS $WARN $FUZZ_LIBDEFS \
    -Dmain=xxl_upstream_main -c $SRCS
$CC $STD $SANITIZER_FLAGS $DEBUG_FLAGS -c mayhem/asan_default_options.c mayhem/watchdog_main.c
$CC $SANITIZER_FLAGS $DEBUG_FLAGS xxl.o repl.o net.o stdlib.o verbs.o \
    asan_default_options.o watchdog_main.o -ldl -lm -o /mayhem/xxl
rm -f ./*.o

# 2) Upstream test suite: xxl built -DDEBUG runs its built-in assertion selftest when given no args.
#    Built with the project's NORMAL flags (no sanitizers, no watchdog rename, real main()) so
#    test.sh is an honest functional oracle; append $COVERAGE_FLAGS (empty by default) for optional
#    coverage measurement of the suite.
gen_compile_h
$CC $STD -O1 $COVERAGE_FLAGS -DTHREAD -DDEBUG $WARN $LIBDEFS $SRCS $LINK -o /mayhem/xxl-test

echo "build.sh: built /mayhem/xxl (fuzz+reproducer, watchdog-bounded) and /mayhem/xxl-test (selftest runner)"
